/*
Deployment script for A2CDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar UserName "A2CUser"
:setvar DatabaseName "A2CDB"
:setvar DefaultFilePrefix "A2CDB"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
IF (SELECT is_default
    FROM   [$(DatabaseName)].[sys].[filegroups]
    WHERE  [name] = N'FileStream') = 0
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            MODIFY FILEGROUP [FileStream] DEFAULT;
    END


GO
USE [$(DatabaseName)];


GO
/*
 Pre-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be executed before the build script.	
 Use SQLCMD syntax to include a file in the pre-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the pre-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
GO

GO
PRINT N'Altering [dbo].[FN_A2C_GETDATETIME]...';


GO


ALTER FUNCTION [dbo].[FN_A2C_GETDATETIME]
(
	@STRINGDATE NVARCHAR(100)
)
RETURNS DATETIME

AS BEGIN

	IF @STRINGDATE IS NULL
		RETURN NULL

	DECLARE @RETURNDATE DATETIME

	SET @STRINGDATE = LTRIM(RTRIM(@STRINGDATE))
		
	IF @STRINGDATE=''
		OR @STRINGDATE='0001-01-01' 
		OR @STRINGDATE='0001-01-01 00:00:00'
		OR @STRINGDATE='0001-01-01T00:00:00+00:00'
		OR @STRINGDATE='0001-01-01T00:00:00Z'
		OR @STRINGDATE='0001-01-01T00:00:01Z'
		RETURN NULL
	
	DECLARE @RETURNDATETIME2 DATETIME2
	SET @RETURNDATETIME2 = CONVERT(DATETIME2,CONVERT(datetimeoffset, @STRINGDATE, 127),1)
	SET @RETURNDATE = CONVERT(DATETIME, @RETURNDATETIME2, 127)

	--IF ISDATE(@STRINGDATE) = 1
	--	SET @RETURNDATE = CONVERT(DATETIME, @STRINGDATE, 127)		
	--ELSE		
	--	SET @RETURNDATE = NULL

	RETURN @RETURNDATE

END
GO
PRINT N'Altering [Version]...';


GO
EXECUTE sp_updateextendedproperty @name = N'Version', @value = N'15.1.11.4';


GO
PRINT N'Refreshing [dbo].[USP_IMPORTPRODUCTCATALOGE]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[USP_IMPORTPRODUCTCATALOGE]';


GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

Update ScreenMasters set ScreenName='ImportCentreCertificate', ScreenDescription='Import Centre Certificate' where ScreenMasterId=1010
GO

GO
PRINT N'Update complete.';


GO
